name: .NET

on:
  push:
    branches: [ "production" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ "production" ]
  workflow_dispatch:
permissions:
  contents: read
  
env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry
jobs:

  build-android:

    runs-on: windows-latest
    name: android build
    steps:
    - uses: actions/checkout@v3
    - name: Setup keystore file
      run: |
        echo "${{ secrets.KEYSTORE_FILE }}" > designpatterns.keystore.asc
        gpg -d --passphrase "${{ secrets.KEYSTORE_GPG_PASSWORD }}" --batch designpatterns.keystore.asc > designpatterns.keystore
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install .NET MAUI
      run:  |
          dotnet nuget locals all --clear 
          dotnet workload install maui android
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Android
      run: dotnet build Nick.DesignPatterns.mobile/Nick.DesignPatterns.mobile.csproj -c Release -f net6.0-android /p:AndroidSigningKeyStore=designpatterns.keystore /p:AndroidSigningKeyAlias=designpatternsKey /p:AndroidSigningKeyPass="${{ secrets.KEYSTORE_PASSWORD }}" /p:AndroidSigningStorePass="${{ secrets.KEYSTORE_PASSWORD }}" --no-restore
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        path: |
          ./**/*.aab
          ./**/*.apk
    - name: Setup Google service file
      run: |
        echo "${{secrets.GOOGLE_CONSOLE_SERVICE_FILE}}" > api-service-account.json.asc
        gpg -d --passphrase "${{ secrets.GOOGLE_CONSOLE_SERVICE_FILE_GPG_PASSWORD }}" --batch api-service-account.json.asc > api-service-account.json
    
  build-ios:
    runs-on: macos-12
    
    name: ios build
    steps: 
      - name: checkout
        uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with: 
          dotnet-version: 6.0.x
      - name: Install .NET MAUI
        run:  |
          dotnet nuget locals all --clear 
          dotnet workload install maui ios maccatalyst

      - name: Restore Dependencies
        run: dotnet restore
        
      - name: Build MAUI iOS
        run: dotnet build Nick.DesignPatterns.mobile/Nick.DesignPatterns.mobile.csproj -c Release -f net6.0-ios --no-restore /p:buildForSimulator=True /p:packageApp=True /p:ArchiveOnBuild=False
        
      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: mauibeach-ios-ci-build
          path: |
            ./**/*.app
    # MAUI Windows Build
  build-windows:
    runs-on: windows-2022
    name: Windows Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build MAUI Windows
        run: dotnet publish  Nick.DesignPatterns.mobile/Nick.DesignPatterns.mobile.csproj -c Release -f net6.0-windows10.0.19041.0 --no-restore

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: mauibeach-windows-ci-build
          path: |
            ./**/*.msix
